### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by 21307369** [axguowen/think-webworker#1]
composer require axguowen/think-webworker     

In PackageDiscoveryTrait.php line 332:

  Could not find a version of package axguowen/think-webworker matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by axguowen** [comment]
版本还没有发布，刚刚发布了，你可以再试下。

**Comment by 21307369** [comment]
TP8
composer require axguowen/think-webworker
./composer.json has been updated
Running composer update axguowen/think-webworker
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1                                                                                                                                                                                                                                                      
    - Root composer.json requires axguowen/think-webworker * -> satisfiable by axguowen/think-webworker[v1.0.0].                                                                                                                                                 
    - axguowen/think-webworker v1.0.0 requires topthink/framework ^6.1 -> found topthink/framework[v6.1.0, ..., v6.1.4] but it conflicts with your root composer.json require (^8.0).                                                                            

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require axguowen/think-webworker:*" to figure out if any version is installable, or "composer require axguowen/think-webworker:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by axguowen** [comment]
这个暂时不支持ThinkPHP8.0哈，先用ThinkPHP6.1安装试试吧

**Comment by axguowen** [comment]
刚刚依赖已经更新了，可以支持PHP8.0，直接安装就好···
